<a href="https://colab.research.google.com/github/tarunvara91-collab/FirstRepository/blob/main/Python_day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
region_sales = {
    "North": [250,300,290],
    "South": [350,310,340],
    "East": [450,490,510],
    "West": [370,380,390]

}

In [9]:
region_sales

{'North': [250, 300, 290],
 'South': [350, 310, 340],
 'East': [450, 490, 510],
 'West': [370, 380, 390]}

In [5]:
region_sales["South"]

[350, 310, 340]

In [10]:
region_sales.keys()

dict_keys(['North', 'South', 'East', 'West'])

In [11]:
region_sales.values()

dict_values([[250, 300, 290], [350, 310, 340], [450, 490, 510], [370, 380, 390]])

In [12]:
region_sales.items()

dict_items([('North', [250, 300, 290]), ('South', [350, 310, 340]), ('East', [450, 490, 510]), ('West', [370, 380, 390])])

In [13]:
products = {"laptop","mouse","keyboard", "mouse"}
products

{'keyboard', 'laptop', 'mouse'}

In [18]:
customers = {"john", "jack", "ajay", "Tarun"}
customers

{'Tarun', 'ajay', 'jack', 'john'}

In [20]:
unique_customer = set(customers)
unique_customer

{'Tarun', 'ajay', 'jack', 'john'}

In [22]:
products_lits = (products)
products_lits

{'keyboard', 'laptop', 'mouse'}

In [24]:
def mysquare(x):
  print(x**2)

In [27]:
mysquare(5)

25

In [28]:
def mysquare_r(x):
  return(x**2)

In [30]:
20 + mysquare_r(10)

120

In [31]:
square = lambda x: x**2

In [32]:
square(5)

25

In [33]:
sales = [500,300,400,700,200]

In [35]:
multiply_by_1_1 = lambda x: 1.1 * x

In [36]:
updated_sales = list(map(lambda x: 1.1 * x, sales))
updated_sales

[550.0, 330.0, 440.00000000000006, 770.0000000000001, 220.00000000000003]

In [41]:
is_greater_than_300 = lambda x: x > 300

In [42]:
filtered_sales = list(filter(lambda x: x>300, sales))
filtered_sales

[500, 400, 700]

In [44]:
data = ["250", "300", "400","None", "500", ""]

In [47]:
cleaned = list(filter(lambda x: x not in(None, ""), data))
cleaned

['250', '300', '400', 'None', '500']

In [53]:
cleaned_int = list(map(lambda x: int(x), filter(lambda x: x.isdigit(), cleaned)))
cleaned_int

[250, 300, 400, 500]

In [54]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [58]:
import pandas

In [61]:
import pandas as pd
pd.read_csv(r"D:\Titanic-Dataset.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Titanic-Dataset.csv'

In [64]:
from google.colab import files

uploaded = files.upload()

Saving Titanic-Dataset.csv to Titanic-Dataset (1).csv

In [66]:
df = pandas.read_csv("/content/Titanic-Dataset.csv")

In [67]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [68]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [69]:
df.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [70]:
df.shape

(891, 12)

In [72]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [75]:
df ["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [78]:
df[["Name","Age"]]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [79]:
df[0:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [80]:
df.drop("Ticket", axis = 1, inplace = True)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,NaN,S

In [85]:
df.head()

,Survived,Pclass,Name,Age,SibSp,Parch,Fare,Embarked
0,0,3,"Braund, Mr. Owen Harris",22.0,1,0,7.2500,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,71.2833,C
2,1,3,"Heikkinen, Miss. Laina",26.0,0,0,7.9250,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,53.1000,S
4,0,3,"Allen, Mr. William Henry",35.0,0,0,8.0500,S

In [86]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

MessageError: Error: credential propagation was unsuccessful